baseURL = 'https://example.org/'
languageCode = 'en-us'
title = "📱 Sofia Toro"
author = "Sofia Toro"
theme = 'hugo-bearblog'

# Generate a nice robots.txt for SEO
enableRobotsTXT = true

[markup.goldmark.renderer]
unsafe = true # Allow HTML in md files
